### ISSUE TITLE
Typescript definition file contains error

### ISSUE THREAD

**Issue by robbaman** [angular/blocking-proxy#30]
The Typescript definition file at `built/lib/blockingproxy.d.ts` contains the following line (line 6 I believe):

    export declare const BP_PREFIX = "bpproxy";

This is not valid for a Typescript definition file (error: Initializers are not allowed in ambient contexts.). I believe the line should be:

    export declare const BP_PREFIX: "bpproxy";

**Comment by heathkit** [comment]
That definition was generated with TypeScript 2.1.5. It seems to not be compatible with TS 2.0.x, but if you upgrade to the latest TypeScript it should be fine.

**Comment by heathkit** [comment]
Since Angular won't support TypeScript 2.1.x until Angular 4, we locked our TS version to 2.0.x. As of release 0.0.5, you shouldn't see this error.
