### ISSUE TITLE
Incorrect "Host" header being forwarded in Selenium requests

### ISSUE THREAD

**Issue by kuangp** [angular/blocking-proxy#44]
I believe `WebdriverProxy` is incorrectly forwarding the `Host` header from `originalRequest` here: https://github.com/angular/blocking-proxy/blob/master/lib/webdriver_proxy.ts#L52

The headers from `originalRequest` includes the `Host` header which is set to the host of the blocking proxy server (eg. `localhost:xxxxx`).  When this forwarded along in the request to selenium, some selenium servers can reject the request since the Host is unknown. I believe this should be explicitly omitted from `options.headers` so it will corrected be inserted by Node Http.

**Comment by heathkit** [comment]
Thanks, I think you're right. I'm a little busy, but I'd welcome a PR to
fix this.

**Comment by kuangp** [comment]
@heathkit I put up the linked PR, please take a look when you get a chance. Thanks!

**Comment by kuangp** [comment]
thanks for the quick response @heathkit, do you know when this fix will be released? It is currently breaking our protractor tests

**Comment by kuangp** [comment]
Hi @heathkit, wondering if you had any updates on when the fix will be released?

**Comment by kuangp** [comment]
@heathkit @juliemr reaching out again to see if either of you have an ETA for releasing this fix?
